---
title: Book Review - Superior
subtitle: ''
summary: I read _Superior_ by Angela Saini in the summer of 2020, during the BLM movement sweeping the globe while the pandemic raged on. Here's the review I wrote the EEB Quarterly (Volume 3, Issue 1)
projects:
author: [Vicki M. Zhang]
date: '2021-01-25'
slug: superior-book-review


categories:
  - PhD 
  - books

tags:
  - msc
  - 2021-Jan
  - race
  - racism
  - book-review

featured: yes
image:
  caption: ""
  focal_point: "smart"
  preview_only: true

links:
  - icon_pack: fab
    name: Originally documented on Notion
    url: 'https://www.notion.so/vmzhang/Superior-Book-Review-2b96392e68b445928df658281b985ef8'
  - icon_pack: fab
    name: Read the EEB Quarterly issues here
    url: 'https://theeebquarterly.github.io/'
  
output:
  blogdown::html_page:
    toc: true
    
    
---
```{r include = FALSE}
knitr::opts_chunk$set(eval = FALSE, echo = FALSE, collapse = TRUE, comment = NA, tidy = FALSE)
```


> Science - or the lack of it - in the end legitimized racism, rather than quashing it. Whatever real and worthwhile questions might have been asked about human difference were unavoidably tainted by politics and economics.

### Superior

Over the last couple months, we, as EEB students, got a front-seat viewing of the more prejudiced aspects of science. I had always operated on the assumption that science is predominantly about discoveries rooted in the data and results, but this illusion has been slowly fracturing.

In [*Superior: The Return of Race Science*](https://www.goodreads.com/book/show/42042093.Superior_The_Return_of_Race_Science), [Angela Saini](https://www.goodreads.com/author/show/4597798.Angela_Saini) documents historical and modern aspects of scientific racism. Using an investigative approach, Saini recounts how race and science intertwine, from archaeology and anthropology to evolution and medicine, and how the misconstruction of science has led to atrocities such as the Holocaust, eugenics, and forced sterilization. And if I wasn't already drawn in by the title and cover, the clear writing, the wittiness, and the personal anecdotes made for an absorbing read.

### Race and Science

This idea that race is inherently biological has been abused, overshadowing good genetic and evolutionary science research. And it's not just old-school, unfunded, irrelevant scientists who are propagating it. These are scientists who are funded millions annually, and whose journal articles are being spread far and wide to endorse racism. For example, several chapters detail how Reginald Ruggles Gates and several other researchers (read: eugenicists and Nazi scientists) established the peer-reviewed journal *Mankind Quarterly*, giving a platform for scientists to spread racist, far right-wing ideas camouflaged as intellectual, truthful science. Jarringly, *Mankind Quarterly* continues to operate due to sizable funding, article submission from researchers, and reviewers and editors. And although the impact factor of *Mankind Quarterly* hovers around 1, it has been influential in legitimizing and spreading racialized rhetoric.

Race science continues to persist in education as well, as detailed in a later chapter. Research into IQ testing corresponding to differences in intelligence between population groups has already opened a whole canister of worms. These theories are exacerbated as specific "intelligence" gene variants (which doesn't exist) are speculated to be rarer in parts of the world, leading to intellectual inferiority (which was refuted by lack of evidence). Intelligence is not bound by discrete genes, nor is it determined solely by genetics. These untrue yet rampant ideas disguised as biology continue to uphold stereotypes and racial prejudices involved in intelligence, resulting in an endless cycle of confirmation biases.

There are differences between humans, just like there are differences between individuals of other species. No two birds look the same. But this variation does not exist on the "race" level, nor can race even be a biological metric; **race is a social construct that does not originate from our DNA**. Although we may already know this, Saini really drives this one main point home.

### Words Matter

*Superior* reads like an extensive news article, and Saini is the journalist. She interviews a **long list** of scientists and academics worldwide to gather a range of perspectives, including apparent racists (or "race realists"), intellectuals cloaking subtle racism as rigorous research, and racial theorists who are obstinately committed to biological differences between race (and some declining to comment). It's to Saini's credit that she presents the many conversations she's had, and then critically disassembles  these fraudulent scientists in an impressive exposé. Intellectual racism has always existed and will continue to persist, and although the vast majority of scientists in ivory towers want to believe that research and discovery transcends politics, we've been proven sorely wrong.

> Our stories get in the way of science. The past is always at the mercy of the present.

The final thing that I appreciated about *Superior* is how Saini really made clear the importance of language. We're in the business of collecting data, sure, but the words we use, and the words that other scientists use, can influence social frameworks. That's how racist scientists have been articulating their work for centuries: using words like "racially pure" and "hybrids" to group people into racial categories. Throughout history, and even in today's day and age, science has been used to back incorrect but strong political and personal beliefs. In the best cases, these beliefs are discouraged, ignored and fade away; in the worst cases, these beliefs spread and cause harm.

> The data, the theories, the facts themselves, are rotated and warped until they fit into a racial framework we can relate to. This is the power of race. It is the power to twist science to its own ends.

What matters is not how the lines are drawn, but what these labels of race mean, because they ultimately translate to an hierarchy of power so powerful that we need to think twice about how unequal and unnatural these systems are. Science is political. It’s imbued with social tension. If there's anything we should remember from academia, it's to question everything.

### Recommendation

Read it. At the very least, you might learn some history; hopefully it also illuminates the power of misconstrued science. In *Superior: The Return of Race Science*, Angela Saini documents historical and modern aspects of scientific racism. Using an investigative approach, Saini recounts how race and science intertwine, from archaeology and anthropology to evolution and medicine, and how the misconstruction of science has led to atrocities such as the Holocaust, eugenics, and forced sterilization. And if I was not already drawn in by the title and cover, the clear writing, the wittiness, and the personal anecdotes made for an absorbing read.
